#########################################################################
# Title:         Cloudbox: Cloudflare Role                              #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---

- name: Set 'record' variable
  set_fact:
    record: "{{ (subdomain == user.domain) | ternary(user.domain,subdomain + '.' + user.domain) }}"
    proxied: "{{ (user.domain == user.domainPrinc) | ternary('yes', 'no') }}"

- name: Set DNS Record
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.login }}"
    zone: "{{ user.domainPrinc }}"
    state: present
    solo: true
    proxied: {{ proxied }}
    type: A
    value: "{{ network.ipv4 }}"
    record: "{{ record }}"

- name: Display DNS Record
  debug:
    msg: "DNS Record for '{{ record }}' set to '{{ network.ipv4 }}'."

- name: Set record for ipv6
  block:
  - name: Set DNS Record ipv6
    cloudflare_dns:
      account_api_token: "{{ cloudflare.api }}"
      account_email: "{{ cloudflare.login }}"
      zone: "{{ user.domainPrinc }}"
      state: present
      solo: true
      proxied: {{ proxied }}
      type: AAAA
      value: "{{ network.ipv6 }}"
      record: "{{ record }}"

  - name: Display DNS Record ipv6
    debug:
      msg: "DNS Record for '{{ record }}' set to '{{ network.ipv6 }}'."
  when: (network.ipv6 is defined) and (network.ipv6|length > 0)
